version: '3.3'
services:
    dp-api-router:
        build:
            context: ../ln-repos/dp-api-router
            dockerfile: Dockerfile.local
        command:
            - reflex
            - -d
            - none
            - -c
            - ./reflex
        volumes:
            - ../ln-repos/dp-api-router:/dp-api-router
        depends_on:
            - kafka-1
            - kafka-2
            - kafka-3
            - mongodb
        ports:
            - 23200:23200
        restart: unless-stopped
        environment:
            MONGODB_BIND_ADDR:        "mongodb:27017"
            KAFKA_ADDR:               "kafka-1:19092,kafka-2:19092,kafka-3:19092"
            ENABLE_PRIVATE_ENDPOINTS: "true"
            ZEBEDEE_URL:              "http://zebedee:8082"
            RECIPE_API_URL:           "http://dp-recipe-api:22300"
            IMPORT_API_URL:           "http://dp-import-api:21800"
            DATASET_API_URL:          "http://dp-dataset-api:22000"
            SERVICE_AUTH_TOKEN:       $SERVICE_AUTH_TOKEN
