version: '3.3'
services:
  mongodb:
    image: mongo:3.6
    ports:
      - 27017:27017
    volumes:
      # Load init script to ensure dbs and collections are created
      - ../mongodb/entrypoint-initdb.d/init.js:/docker-entrypoint-initdb.d/init.js:ro
  postgres:
    build: ../postgres
    environment: 
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432
  minio:
    image: 'bitnami/minio:latest'
    volumes:
      - ../minio/data:/data
    ports:
      - '9001:9000'
    environment:
      - MINIO_ACCESS_KEY=minio-access-key
      - MINIO_SECRET_KEY=minio-secret-key
      - MINIO_DEFAULT_BUCKETS=public-bucket,private-bucket
  vault:
    image: 'hashicorp/vault:latest'
    ports:
      - '8200:8200'
    entrypoint: vault server -dev -dev-kv-v1
    volumes:
      - ../vault/config:/vault/config
    environment:
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_DEV_ROOT_TOKEN_ID=0000-0000-0000-0000
  # im not 100% what these are for - es - site search i think
  # elasticsearch:
  #   image: elasticsearch:2.4.2
  #   ports:
  #    - "9300:9300"
  #    - "9200:9200"
  #   environment:
  #    - "discovery.type=single-node"
  # cmdelasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
  #   ports:
  #     # Set alternative ports to prevent port clash.
  #     - 10300:9300
  #     - 10200:9200
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  # sitewideelasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
  #   ports:
  #     # Set alternative ports to prevent port clash.
  #     - 11300:9300
  #     - 11200:9200
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #     - "discovery.type=single-node"
  # highcharts:
  #   image: onsdigital/highcharts-export-node
  #   ports:
  #    - "9999:8080"
  # mathjax:
  #   image: onsdigital/mathjax-api
  #   ports:
  #     - "8888:8080"
  # redis:
  #   image: redis:6
  #   command: redis-server --requirepass default
  #   ports:
  #     - "6379:6379"